const strings = {
  common: {
    back: "Back",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    loading: "Loading...",
    search: "Search",
    clear: "Clear",
    remove: "Remove",
    or: "or",
    noResults: "No books found.",
    published: "Published",
    draft: "Draft",
  },

  header: {
    skipLink: "Skip to main content",
    logoAlt: "SaatSaheli Saraswati logo",
    navHome: "Home",
    navAbout: "About",
    navBooks: "Books",
    navSearch: "Search",
    navLogin: "Login",
    dropdownOptions: [
      { label: "Contact Us", value: "/contacts" },
      { label: "Site Policies", value: "/policies" },
      { label: "Feedback", value: "/contacts" },
    ],
    myAccount: "My Account",
    logout: "Logout",
  },

  footer: {
    copyright: "\u00A9 2026 SaatSaheli. All rights reserved.",
  },

  home: {
    welcomeHeading: "Welcome to Saat Saheli \u2013 A Community for Passion and Creativity!",
    searchHeading: "Search Books",
    labelBookId: "Book ID",
    labelBookName: "Book Name",
    labelAuthorName: "Author Name",
    labelStatus: "Status",
    placeholderBookId: "e.g. 1",
    placeholderTitle: "Search by title...",
    placeholderAuthor: "Search by author...",
    statusAll: "All",
    statusPublished: "Published",
    statusDraft: "Draft",
    searchButton: "Search",
    clearButton: "Clear",
    searchError: "Failed to search books. Please try again.",
    searching: "Searching...",
    resultsHeading: "Results",
    resultsCount: (n) => `${n} book${n !== 1 ? "s" : ""} found`,
    noResults: "No books match your search criteria.",
    authorPrefix: "Author: ",
    idPrefix: "ID: ",
    createdPrefix: "Created: ",
    modifiedPrefix: "Modified: ",
    viewingBook: (id) => `Viewing: Book #${id}`,
    viewLabel: (title) => `View ${title}`,
    searchAriaLabel: "Search books",
  },

  about: {
    heading: "About SaatSaheli",
    description:
      "Do you have a hobby, skill, or passion you can't stop talking about? Whether you're an artist, musician, writer, tech enthusiast, or simply someone who loves trying new things, Saat Saheli is the perfect creative community for you to share, learn, and connect through hobby sharing.",
    tags: ["Art", "Music", "Writing", "Tech", "Creativity", "Community"],
  },

  contact: {
    heading: "Contact Us",
    subheading: "Questions or Comments?",
    intro:
      "Contact us today to join our creative community, create your own page, share your hobbies, and explore a world of talent and creativity with Saat Saheli!",
    labelName: "Name",
    labelEmail: "Email",
    labelMessage: "Message",
    placeholderName: "Your name",
    placeholderEmail: "Your email",
    placeholderMessage: "Write your message...",
    sendButton: "Send Message",
    successMessage: "Thank you! Your message is ready to send.",
    emailPrompt: "Or email us directly at",
    email: "saheli@saatsaheli.com",
    mailtoSubject: (name) => `Contact from ${name}`,
    mailtoBody: (message, name, email) => `${message}\n\nFrom: ${name} (${email})`,
  },

  sitePolicies: {
    heading: "Site Policies",
    termsHeading: "Terms of Use",
    termsBody:
      "By accessing and using SaatSaheli, you agree to comply with these terms. SaatSaheli is a creative community platform for sharing hobbies, skills, and passions. All users must use the platform respectfully and in accordance with applicable laws.",
    contentHeading: "Content Policy",
    contentIntro: "Users are responsible for the content they publish. Content must be:",
    contentRules: [
      "Original or properly attributed to the creator",
      "Free from hate speech, harassment, or harmful material",
      "Appropriate for a general audience",
      "Not infringing on any copyright or intellectual property rights",
    ],
    contentFooter:
      "SaatSaheli reserves the right to remove any content that violates these guidelines.",
    privacyHeading: "Privacy Policy",
    privacyBody:
      "We value your privacy. SaatSaheli collects only the information necessary to provide our services, including your name, email address, and content you create. We do not sell or share your personal information with third parties. Your data is stored securely and used solely for operating the platform.",
    accountHeading: "Account Policy",
    accountRules: [
      "Users must provide accurate information when creating an account",
      "Each user may maintain one account",
      "Users are responsible for maintaining the security of their account",
      "Accounts found violating site policies may be suspended or removed",
    ],
    ipHeading: "Intellectual Property",
    ipBody:
      "All content created and published on SaatSaheli remains the intellectual property of its creator. By publishing on our platform, you grant SaatSaheli a non-exclusive license to display your content within the platform. You may remove your content at any time.",
    contactHeading: "Contact",
    contactBody: "For questions about these policies, please reach out to us at",
    contactEmail: "saheli@saatsaheli.com",
    lastUpdated: "Last updated: February 2026",
  },

  login: {
    brand: "Saat Saheli",
    tagline: "Your digital book platform",
    logInHeading: "Log In",
    createAccountHeading: "Create Account",
    labelEmail: "Email",
    labelPassword: "Password",
    labelFirstName: "First Name *",
    labelLastName: "Last Name",
    labelSignupEmail: "Email *",
    labelPhone: "Phone Number",
    labelSignupPassword: "Password *",
    labelConfirmPassword: "Confirm Password *",
    placeholderEmail: "Enter your email",
    placeholderPassword: "Enter your password",
    placeholderFirstName: "First name",
    placeholderLastName: "Last name",
    placeholderPhone: "(optional)",
    placeholderSignupPassword: "At least 6 characters",
    placeholderConfirmPassword: "Re-enter your password",
    logInButton: "Log In",
    loggingIn: "Logging in...",
    createAccountButton: "Create Account",
    creatingAccount: "Creating Account...",
    errorEmailPasswordRequired: "Email and password are required.",
    errorSignupRequired: "First name, email, and password are required.",
    errorPasswordMismatch: "Passwords do not match.",
    errorPasswordLength: "Password must be at least 6 characters.",
    errorLoginFailed: "Login failed. Please try again.",
    errorSignupFailed: "Signup failed. Please try again.",
    errorGoogleFailed: "Google sign-in failed. Please try again.",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
    switchToSignup: "Create Account",
    switchToLogin: "Log In",
  },

  bookManager: {
    heading: "Book Manager",
    createNewBook: "Create New Book",
    myDrafts: "My Drafts",
    allMyBooks: "All My Books",
    createHeading: "Create New Book",
    placeholderTitle: "Enter book title...",
    createButton: "Create Book",
    creating: "Creating...",
    draftsHeading: "My Drafts",
    allBooksHeading: "All My Books",
    editHeading: "Edit Book",
    previewHeading: (title) => `Preview: ${title}`,
    noDrafts: "No drafts found.",
    noBooks: "No books found.",
    saveTitle: "Save Title",
    saveAsDraft: "Save as Draft",
    publish: "Publish",
    preview: "Preview",
    deleteBook: "Delete Book",
    addNewPage: "Add New Page",
    placeholderPageNumber: "Page #",
    placeholderContent: "Page content...",
    placeholderEditContent: "Content",
    addPage: "Add Page",
    pagesCount: (n) => `Pages (${n})`,
    emptyPage: "(empty)",
    image1Label: "Image 1",
    image2Label: "Image 2",
    image1Alt: "img1",
    image2Alt: "img2",
    chooseFile: "Choose File",
    uploading: "Uploading...",
    textFormatting: "Text Formatting",
    fontSans: "Sans-serif",
    fontSerif: "Serif",
    fontMono: "Monospace",
    fontCursive: "Cursive",
    ariaFontFamily: "Font family",
    ariaFontSize: "Font size",
    ariaFontColor: "Font color",
    modified: "Modified: ",
    backToMenu: "Back to Menu",
    backToEdit: "Back to Edit",
    msgImageUploaded: "Image uploaded!",
    msgUploadFailed: (err) => `Upload failed: ${err}`,
    msgEnterTitle: "Please enter a book title",
    msgBookCreated: "Book created as Draft!",
    msgCreateFailed: (err) => `Failed to create book: ${err}`,
    msgTitleUpdated: "Title updated!",
    msgTitleFailed: "Failed to update title",
    msgPublished: "Book published!",
    msgPublishFailed: "Failed to publish",
    msgDraftSaved: "Saved as draft!",
    msgDraftFailed: "Failed to save draft",
    confirmDeleteBook: "Are you sure you want to delete this book and all its pages?",
    msgBookDeleted: "Book deleted!",
    msgDeleteBookFailed: "Failed to delete book",
    msgPageNumberRequired: "Page number is required",
    msgPageAdded: "Page added!",
    msgAddPageFailed: "Failed to add page",
    msgPageUpdated: "Page updated!",
    msgUpdatePageFailed: "Failed to update page",
    confirmDeletePage: "Delete this page?",
    msgPageDeleted: "Page deleted!",
    msgDeletePageFailed: "Failed to delete page",
  },

  searchBooks: {
    heading: "Search Books",
    placeholderBookId: "Book ID",
    placeholderTitle: "Title",
    placeholderAuthor: "Author name",
    ariaBookId: "Search by book ID",
    ariaTitle: "Search by title",
    ariaAuthor: "Search by author",
    ariaStatus: "Filter by status",
    statusAll: "All Statuses",
    statusDraft: "Draft",
    statusPublished: "Published",
    statusArchived: "Archived",
    searching: "Searching...",
    searchButton: "Search",
    clearButton: "Clear",
    resultsHeading: (n) => `Results (${n})`,
    noResults: "No books found.",
    thId: "ID",
    thTitle: "Title",
    thAuthor: "Author",
    thStatus: "Status",
    thModified: "Modified",
    emptyAuthor: "\u2014",
    booksHeading: (n) => `Books (${n})`,
    backToTable: "Back to Table",
    byAuthor: (name) => `by ${name}`,
  },

  readBook: {
    backToSearch: "Back to Search",
  },

  flipBook: {
    pageHeading: (n) => `Page ${n}`,
    pageImageAlt: (n, i) => `Page ${n} - ${i}`,
  },

  pageLayoutEditor: {
    labelBar: "Page Layout Editor \u2014 drag images to position, drag corner to resize",
    image1Label: "Image 1",
    image2Label: "Image 2",
  },

  dropdown: {
    defaultText: "Select",
  },
};

export default strings;
