export const en = {
  common: {
    back: "Back",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    loading: "Loading...",
    search: "Search",
    clear: "Clear",
    remove: "Remove",
    or: "or",
    noResults: "No books found.",
    published: "Published",
    draft: "Draft",
  },

  header: {
    skipLink: "Skip to main content",
    logoAlt: "SaatSaheli logo",
    siteName: "Saat Saheli",
    siteTagline: "Welcome to Saat Saheli \u2013 A Community for Passion and Creativity!",
    navHome: "Home",
    navAbout: "About",
    navBooks: "Books",
    navSearch: "Search",
    navChat: "Chat",
    navAdmin: "Admin",
    navLogin: "Login",
    dropdownOptions: [
      { label: "Contact Us", value: "/contacts" },
      { label: "Site Policies", value: "/policies" },
      { label: "Feedback", value: "/contacts" },
    ],
    myAccount: "My Account",
    logout: "Logout",
    language: "Language",
  },

  footer: {
    contactUs: "Contact Us",
    sitePolicies: "Site Policies",
    feedback: "Feedback",
    copyright: "\u00A9 2026 SaatSaheli. All rights reserved.",
  },

  home: {
    welcomeHeading: "Welcome to Saat Saheli \u2013 A Community for Passion and Creativity!",
    searchHeading: "Search Books",
    labelBookId: "Book ID",
    labelBookName: "Book Name",
    labelAuthorName: "Author Name",
    labelStatus: "Status",
    placeholderBookId: "e.g. 1",
    placeholderTitle: "Search by title...",
    placeholderAuthor: "Search by author...",
    statusAll: "All",
    statusPublished: "Published",
    statusDraft: "Draft",
    searchButton: "Search",
    clearButton: "Clear",
    searchError: "Failed to search books. Please try again.",
    searching: "Searching...",
    resultsHeading: "Results",
    resultsCount: (n) => `${n} book${n !== 1 ? "s" : ""} found`,
    noResults: "No books match your search criteria.",
    authorPrefix: "Author: ",
    idPrefix: "ID: ",
    createdPrefix: "Created: ",
    modifiedPrefix: "Modified: ",
    viewingBook: (id) => `Viewing: Book #${id}`,
    viewLabel: (title) => `View ${title}`,
    searchAriaLabel: "Search books",
  },

  about: {
    heading: "About SaatSaheli",
    description:
      "Do you have a hobby, skill, or passion you can't stop talking about? Whether you're an artist, musician, writer, tech enthusiast, or simply someone who loves trying new things, Saat Saheli is the perfect creative community for you to share, learn, and connect through hobby sharing.",
    tags: ["Art", "Music", "Writing", "Tech", "Creativity", "Community"],
  },

  contact: {
    heading: "Contact Us",
    subheading: "Questions or Comments?",
    intro:
      "Contact us today to join our creative community, create your own page, share your hobbies, and explore a world of talent and creativity with Saat Saheli!",
    labelName: "Name",
    labelEmail: "Email",
    labelMessage: "Message",
    placeholderName: "Your name",
    placeholderEmail: "Your email",
    placeholderMessage: "Write your message...",
    sendButton: "Send Message",
    successMessage: "Thank you! Your message is ready to send.",
    emailPrompt: "Or email us directly at",
    email: "saheli@saatsaheli.com",
    mailtoSubject: (name) => `Contact from ${name}`,
    mailtoBody: (message, name, email) => `${message}\n\nFrom: ${name} (${email})`,
  },

  sitePolicies: {
    heading: "Site Policies",
    termsHeading: "Terms of Use",
    termsBody:
      "By accessing and using SaatSaheli, you agree to comply with these terms. SaatSaheli is a creative community platform for sharing hobbies, skills, and passions. All users must use the platform respectfully and in accordance with applicable laws.",
    contentHeading: "Content Policy",
    contentIntro: "Users are responsible for the content they publish. Content must be:",
    contentRules: [
      "Original or properly attributed to the creator",
      "Free from hate speech, harassment, or harmful material",
      "Appropriate for a general audience",
      "Not infringing on any copyright or intellectual property rights",
    ],
    contentFooter:
      "SaatSaheli reserves the right to remove any content that violates these guidelines.",
    privacyHeading: "Privacy Policy",
    privacyBody:
      "We value your privacy. SaatSaheli collects only the information necessary to provide our services, including your name, email address, and content you create. We do not sell or share your personal information with third parties. Your data is stored securely and used solely for operating the platform.",
    accountHeading: "Account Policy",
    accountRules: [
      "Users must provide accurate information when creating an account",
      "Each user may maintain one account",
      "Users are responsible for maintaining the security of their account",
      "Accounts found violating site policies may be suspended or removed",
    ],
    ipHeading: "Intellectual Property",
    ipBody:
      "All content created and published on SaatSaheli remains the intellectual property of its creator. By publishing on our platform, you grant SaatSaheli a non-exclusive license to display your content within the platform. You may remove your content at any time.",
    contactHeading: "Contact",
    contactBody: "For questions about these policies, please reach out to us at",
    contactEmail: "saheli@saatsaheli.com",
    lastUpdated: "Last updated: February 2026",
  },

  login: {
    brand: "Saat Saheli",
    tagline: "Your digital book platform",
    logInHeading: "Log In",
    createAccountHeading: "Create Account",
    labelEmail: "Email",
    labelPassword: "Password",
    labelFirstName: "First Name *",
    labelLastName: "Last Name",
    labelSignupEmail: "Email *",
    labelPhone: "Phone Number",
    labelSignupPassword: "Password *",
    labelConfirmPassword: "Confirm Password *",
    placeholderEmail: "Enter your email",
    placeholderPassword: "Enter your password",
    placeholderFirstName: "First name",
    placeholderLastName: "Last name",
    placeholderPhone: "(optional)",
    placeholderSignupPassword: "At least 6 characters",
    placeholderConfirmPassword: "Re-enter your password",
    logInButton: "Log In",
    loggingIn: "Logging in...",
    createAccountButton: "Create Account",
    creatingAccount: "Creating Account...",
    errorEmailPasswordRequired: "Email and password are required.",
    errorSignupRequired: "First name, email, and password are required.",
    errorPasswordMismatch: "Passwords do not match.",
    errorPasswordLength: "Password must be at least 6 characters.",
    errorLoginFailed: "Login failed. Please try again.",
    errorSignupFailed: "Signup failed. Please try again.",
    errorGoogleFailed: "Google sign-in failed. Please try again.",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
    switchToSignup: "Create Account",
    switchToLogin: "Log In",
  },

  bookManager: {
    heading: "Book Manager",
    createNewBook: "Create New Book",
    myDrafts: "My Drafts",
    allMyBooks: "All My Books",
    createHeading: "Create New Book",
    placeholderTitle: "Enter book title...",
    createButton: "Create Book",
    creating: "Creating...",
    draftsHeading: "My Drafts",
    allBooksHeading: "All My Books",
    editHeading: "Edit Book",
    previewHeading: (title) => `Preview: ${title}`,
    noDrafts: "No drafts found.",
    noBooks: "No books found.",
    saveTitle: "Save Title",
    saveAsDraft: "Save as Draft",
    publish: "Publish",
    preview: "Preview",
    deleteBook: "Delete Book",
    addNewPage: "Add New Page",
    placeholderPageNumber: "Page #",
    placeholderContent: "Page content...",
    placeholderEditContent: "Content",
    addPage: "Add Page",
    pagesCount: (n) => `Pages (${n})`,
    emptyPage: "(empty)",
    image1Label: "Image 1",
    image2Label: "Image 2",
    image1Alt: "img1",
    image2Alt: "img2",
    chooseFile: "Choose File",
    uploading: "Uploading...",
    textFormatting: "Text Formatting",
    fontSans: "Sans-serif",
    fontSerif: "Serif",
    fontMono: "Monospace",
    fontCursive: "Cursive",
    ariaFontFamily: "Font family",
    ariaFontSize: "Font size",
    ariaFontColor: "Font color",
    modified: "Modified: ",
    backToMenu: "Back to Menu",
    backToEdit: "Back to Edit",
    msgImageUploaded: "Image uploaded!",
    msgUploadFailed: (err) => `Upload failed: ${err}`,
    msgEnterTitle: "Please enter a book title",
    msgBookCreated: "Book created as Draft!",
    msgCreateFailed: (err) => `Failed to create book: ${err}`,
    msgTitleUpdated: "Title updated!",
    msgTitleFailed: "Failed to update title",
    msgPublished: "Book published!",
    msgPublishFailed: "Failed to publish",
    msgDraftSaved: "Saved as draft!",
    msgDraftFailed: "Failed to save draft",
    confirmDeleteBook: "Are you sure you want to delete this book and all its pages?",
    msgBookDeleted: "Book deleted!",
    msgDeleteBookFailed: "Failed to delete book",
    msgPageNumberRequired: "Page number is required",
    msgPageAdded: "Page added!",
    msgAddPageFailed: "Failed to add page",
    msgPageUpdated: "Page updated!",
    msgUpdatePageFailed: "Failed to update page",
    confirmDeletePage: "Delete this page?",
    msgPageDeleted: "Page deleted!",
    msgDeletePageFailed: "Failed to delete page",
    createWithAI: "Create with AI",
    generatingImage: "Generating...",
    msgImageGenerated: "AI image generated!",
    msgGenerateFailed: (err) => `AI generation failed: ${err}`,
    msgEmptyContentForAI: "Please enter a description for the AI image.",
    aiPromptDialog: "Describe the image you want to generate:",
    imageStyleLabel: "Image Style",
    imageStyles: [
      { value: "general", label: "General" },
      { value: "children", label: "Children's Book" },
      { value: "poetry", label: "Poetry" },
      { value: "story", label: "Story" },
      { value: "art", label: "Fine Art" },
      { value: "science", label: "Science" },
      { value: "politics", label: "Politics" },
      { value: "technology", label: "Technology" },
      { value: "geography", label: "Geography" },
      { value: "history", label: "History" },
      { value: "fantasy", label: "Fantasy" },
      { value: "realistic", label: "Realistic" },
    ],
    createFromDocument: "Create from Document",
    uploadDocHeading: "Create Book from Document",
    uploadDocHint: "Upload a PDF or Word document (.pdf, .docx, .doc). The text will be extracted and split into pages automatically.",
    uploadDocButton: "Upload & Create Book",
    uploadingDoc: "Processing document...",
    msgBookFromDoc: (n) => `Book created with ${n} pages from document!`,
    msgDocUploadFailed: (err) => `Document upload failed: ${err}`,
  },

  searchBooks: {
    heading: "Search Books",
    placeholderBookId: "Book ID",
    placeholderTitle: "Title",
    placeholderAuthor: "Author name",
    ariaBookId: "Search by book ID",
    ariaTitle: "Search by title",
    ariaAuthor: "Search by author",
    ariaStatus: "Filter by status",
    statusAll: "All Statuses",
    statusDraft: "Draft",
    statusPublished: "Published",
    statusArchived: "Archived",
    searching: "Searching...",
    searchButton: "Search",
    clearButton: "Clear",
    resultsHeading: (n) => `Results (${n})`,
    noResults: "No books found.",
    thId: "ID",
    thTitle: "Title",
    thAuthor: "Author",
    thStatus: "Status",
    thModified: "Modified",
    emptyAuthor: "\u2014",
    booksHeading: (n) => `Books (${n})`,
    backToTable: "Back to Table",
    byAuthor: (name) => `by ${name}`,
  },

  account: {
    heading: "My Account",
    userInfoHeading: "Profile",
    labelName: "Name",
    labelEmail: "Email",
    createProfile: "Create My Profile",
    editProfile: "Edit Profile",
    viewPublicProfile: "View Public Profile",
    labelHeadline: "Headline",
    labelLocation: "Location",
    labelBio: "About Me",
    booksHeading: "My Books",
    thTitle: "Title",
    thStatus: "Status",
    thCreated: "Created",
    thModified: "Modified",
    thActions: "Actions",
    editButton: "Edit",
    emptyState: "You haven't created any books yet.",
    loading: "Loading your books...",
    error: "Failed to load books. Please try again.",
    loginRequired: "Please log in to view your account.",
  },

  profile: {
    heading: "Create My Profile",
    editHeading: "Edit Profile",
    labelDisplayName: "Full Name / Display Name",
    labelHeadline: "Headline",
    labelProfileImage: "Profile Image",
    labelLocation: "Location",
    labelBio: "About Me / Bio",
    placeholderDisplayName: "Your display name",
    placeholderHeadline: "e.g., Passionate Weaver of Stories and Silk",
    placeholderLocation: "City, Country",
    placeholderBio: "Tell your story in your own words...",
    imageAlt: "Profile image",
    uploading: "Uploading...",
    imageUploaded: "Image uploaded!",
    imageUploadFailed: "Failed to upload image.",
    nameRequired: "Display name is required.",
    saveButton: "Save Profile",
    saving: "Saving...",
    saved: "Profile saved!",
    saveFailed: "Failed to save profile. Please try again.",
    backToAccount: "Back to Account",
    loading: "Loading profile...",
    loadError: "Failed to load profile.",
    loginRequired: "Please log in to edit your profile.",
  },

  publicProfile: {
    loading: "Loading profile...",
    notFound: "Profile not found.",
    memberSince: "Member since",
    booksHeading: "Published Books",
    noBooks: "No published books yet.",
  },

  publicBooks: {
    heading: "Published Books",
    loading: "Loading books...",
    error: "Failed to load books. Please try again.",
    emptyState: "No published books available yet.",
    readButton: "Read",
    backToBooks: "Back to Books",
    home: "Home",
    loginPrompt: "Log in to create and manage your own books.",
  },

  readBook: {
    backToSearch: "Back to Search",
    home: "Home",
    books: "Books",
    prevBook: "Previous Book",
    nextBook: "Next Book",
  },

  flipBook: {
    pageHeading: (n) => `Page ${n}`,
    pageImageAlt: (n, i) => `Page ${n} - ${i}`,
    prevPage: "Previous page",
    nextPage: "Next page",
    firstPage: "First page",
    lastPage: "Last page",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    zoomReset: "Reset zoom",
  },

  pageLayoutEditor: {
    labelBar: "Page Layout Editor \u2014 drag images to position, drag corner to resize",
    image1Label: "Image 1",
    image2Label: "Image 2",
  },

  category: {
    comingSoon: (title) => `${title} की सामग्री जल्द आ रही है। बने रहें!`,
    backToHome: "Back to Home",
  },

  categoryPage: {
    tabBrowse: "Browse",
    tabCreate: "Create",
    tabMyBooks: "My Books",
    noPublished: "No published books in this category yet.",
    beFirst: "Be the first to create one!",
    loginToCreate: "Log in to create content",
    createHeading: (title) => `Create a ${title} Book`,
    titlePlaceholder: "Enter book title...",
    createButton: "Create Book",
    createHint: "Your book will be created as a draft. Use the Books page to add pages, images, and publish.",
    myBooksHeading: (title) => `My ${title} Books`,
    noMyBooks: "You haven't created any books in this category yet.",
    createFirst: "Create your first one",
    enterTitle: "Please enter a title",
    bookCreated: "Book created as Draft!",
    createFailed: "Failed to create book",
    confirmDelete: "Delete this book?",
    bookDeleted: "Book deleted!",
    deleteFailed: "Failed to delete book",
    bookPublished: "Book published!",
    publishFailed: "Failed to publish",
    backToBrowse: "Back",
    descriptions: {
      art: "Explore and share Art content with the community",
      music: "Explore and share Music content with the community",
      writing: "Explore and share Writing content with the community",
      tech: "Explore and share Technology content with the community",
      creativity: "Explore and share Creativity content with the community",
      community: "Explore and share Community content with the community",
    },
  },

  techPage: {
    heading: "Tech",
    description: "Explore technology topics across multiple dimensions",
    tabTechnical: "Technical",
    tabCareer: "Career & Industry",
    tabCommunity: "Community & Representation",
    tabOther: "Other",
    descTechnical: "Programming, coding tutorials, tools, and technical resources",
    descCareer: "Tech careers, job skills, industry insights, and professional growth",
    descCommunity: "Women in tech, diversity, inclusion, and representation stories",
    descOther: "Miscellaneous tech topics, trends, and interesting finds",
    comingSoon: "Content coming soon. Stay tuned!",
  },

  admin: {
    heading: "Admin Dashboard",
    tabStats: "Stats",
    tabUsers: "Users",
    tabBooks: "Books",
    totalUsers: "Total Users",
    activeUsers: "Active Users",
    blockedUsers: "Blocked Users",
    adminCount: "Admins",
    totalBooks: "Total Books",
    publishedBooks: "Published",
    draftBooks: "Drafts",
    colName: "Name",
    colEmail: "Email",
    colRole: "Role",
    colStatus: "Status",
    colLastLogin: "Last Login",
    colActions: "Actions",
    colTitle: "Title",
    colAuthor: "Author",
    colBookStatus: "Status",
    colModified: "Modified",
    roleUpdated: "Role updated!",
    roleUpdateFailed: "Failed to update role",
    statusUpdated: "Status updated!",
    statusUpdateFailed: "Failed to update status",
    confirmDeleteBook: "Are you sure you want to delete this book?",
    bookDeleted: "Book deleted!",
    bookDeleteFailed: "Failed to delete book",
  },

  chat: {
    roomsHeading: "Chat Rooms",
    noMessages: "No messages yet. Start the conversation!",
    selectRoom: "Select a room to start chatting",
    placeholder: "Type a message...",
    sendButton: "Send",
    sending: "...",
    deleteMessage: "Delete",
  },

  dropdown: {
    defaultText: "Select",
  },
};

export const hi = {
  common: {
    back: "वापस",
    edit: "संपादित करें",
    delete: "हटाएं",
    save: "सहेजें",
    cancel: "रद्द करें",
    loading: "लोड हो रहा है...",
    search: "खोजें",
    clear: "साफ़ करें",
    remove: "हटाएं",
    or: "या",
    noResults: "कोई किताब नहीं मिली।",
    published: "प्रकाशित",
    draft: "ड्राफ्ट",
  },

  header: {
    skipLink: "मुख्य सामग्री पर जाएं",
    logoAlt: "सातसहेली सरस्वती लोगो",
    siteName: "सात सहेली",
    siteTagline: "सात सहेली में आपका स्वागत है \u2013 जुनून और रचनात्मकता का समुदाय!",
    navHome: "होम",
    navAbout: "हमारे बारे में",
    navBooks: "किताबें",
    navSearch: "खोजें",
    navChat: "चैट",
    navAdmin: "व्यवस्थापक",
    navLogin: "लॉगिन",
    dropdownOptions: [
      { label: "संपर्क करें", value: "/contacts" },
      { label: "साइट नीतियां", value: "/policies" },
      { label: "प्रतिक्रिया", value: "/contacts" },
    ],
    myAccount: "मेरा खाता",
    logout: "लॉगआउट",
    language: "भाषा",
  },

  footer: {
    contactUs: "संपर्क करें",
    sitePolicies: "साइट नीतियां",
    feedback: "प्रतिक्रिया",
    copyright: "\u00A9 2026 सातसहेली। सर्वाधिकार सुरक्षित।",
  },

  home: {
    welcomeHeading: "सात सहेली में आपका स्वागत है \u2013 जुनून और रचनात्मकता का समुदाय!",
    searchHeading: "किताबें खोजें",
    labelBookId: "किताब आईडी",
    labelBookName: "किताब का नाम",
    labelAuthorName: "लेखक का नाम",
    labelStatus: "स्थिति",
    placeholderBookId: "जैसे 1",
    placeholderTitle: "शीर्षक से खोजें...",
    placeholderAuthor: "लेखक से खोजें...",
    statusAll: "सभी",
    statusPublished: "प्रकाशित",
    statusDraft: "ड्राफ्ट",
    searchButton: "खोजें",
    clearButton: "साफ़ करें",
    searchError: "किताबें खोजने में विफल। कृपया पुनः प्रयास करें।",
    searching: "खोज रहे हैं...",
    resultsHeading: "परिणाम",
    resultsCount: (n) => `${n} किताब${n !== 1 ? "ें" : ""} मिली${n !== 1 ? "ं" : ""}`,
    noResults: "आपकी खोज से कोई किताब नहीं मिली।",
    authorPrefix: "लेखक: ",
    idPrefix: "आईडी: ",
    createdPrefix: "बनाई गई: ",
    modifiedPrefix: "संशोधित: ",
    viewingBook: (id) => `देख रहे हैं: किताब #${id}`,
    viewLabel: (title) => `${title} देखें`,
    searchAriaLabel: "किताबें खोजें",
  },

  about: {
    heading: "सातसहेली के बारे में",
    description:
      "क्या आपके पास कोई शौक, कौशल या जुनून है जिसके बारे में आप बात करते नहीं थकते? चाहे आप कलाकार हों, संगीतकार, लेखक, तकनीकी उत्साही, या बस कुछ नया करने का शौक रखते हों, सात सहेली आपके लिए एकदम सही रचनात्मक समुदाय है जहां आप अपने शौक साझा कर सकते हैं, सीख सकते हैं और जुड़ सकते हैं।",
    tags: ["कला", "संगीत", "लेखन", "तकनीक", "रचनात्मकता", "समुदाय"],
  },

  contact: {
    heading: "संपर्क करें",
    subheading: "प्रश्न या टिप्पणियां?",
    intro:
      "हमारे रचनात्मक समुदाय से जुड़ने, अपना पेज बनाने, अपने शौक साझा करने और सात सहेली के साथ प्रतिभा और रचनात्मकता की दुनिया का पता लगाने के लिए आज ही संपर्क करें!",
    labelName: "नाम",
    labelEmail: "ईमेल",
    labelMessage: "संदेश",
    placeholderName: "आपका नाम",
    placeholderEmail: "आपका ईमेल",
    placeholderMessage: "अपना संदेश लिखें...",
    sendButton: "संदेश भेजें",
    successMessage: "धन्यवाद! आपका संदेश भेजने के लिए तैयार है।",
    emailPrompt: "या हमें सीधे ईमेल करें",
    email: "saheli@saatsaheli.com",
    mailtoSubject: (name) => `${name} से संपर्क`,
    mailtoBody: (message, name, email) => `${message}\n\nसे: ${name} (${email})`,
  },

  sitePolicies: {
    heading: "साइट नीतियां",
    termsHeading: "उपयोग की शर्तें",
    termsBody:
      "सातसहेली का उपयोग करके, आप इन शर्तों का पालन करने के लिए सहमत हैं। सातसहेली शौक, कौशल और जुनून साझा करने के लिए एक रचनात्मक समुदाय मंच है। सभी उपयोगकर्ताओं को सम्मानपूर्वक और लागू कानूनों के अनुसार मंच का उपयोग करना चाहिए।",
    contentHeading: "सामग्री नीति",
    contentIntro: "उपयोगकर्ता अपनी प्रकाशित सामग्री के लिए जिम्मेदार हैं। सामग्री होनी चाहिए:",
    contentRules: [
      "मूल या रचनाकार को उचित रूप से श्रेय दी गई",
      "घृणा भाषण, उत्पीड़न या हानिकारक सामग्री से मुक्त",
      "सामान्य दर्शकों के लिए उपयुक्त",
      "किसी भी कॉपीराइट या बौद्धिक संपदा अधिकारों का उल्लंघन नहीं करती",
    ],
    contentFooter:
      "सातसहेली इन दिशानिर्देशों का उल्लंघन करने वाली किसी भी सामग्री को हटाने का अधिकार रखती है।",
    privacyHeading: "गोपनीयता नीति",
    privacyBody:
      "हम आपकी गोपनीयता को महत्व देते हैं। सातसहेली केवल हमारी सेवाएं प्रदान करने के लिए आवश्यक जानकारी एकत्र करती है, जिसमें आपका नाम, ईमेल पता और आपके द्वारा बनाई गई सामग्री शामिल है। हम आपकी व्यक्तिगत जानकारी तीसरे पक्ष को नहीं बेचते या साझा नहीं करते। आपका डेटा सुरक्षित रूप से संग्रहीत है और केवल मंच के संचालन के लिए उपयोग किया जाता है।",
    accountHeading: "खाता नीति",
    accountRules: [
      "खाता बनाते समय उपयोगकर्ताओं को सही जानकारी देनी होगी",
      "प्रत्येक उपयोगकर्ता एक खाता रख सकता है",
      "उपयोगकर्ता अपने खाते की सुरक्षा बनाए रखने के लिए जिम्मेदार हैं",
      "साइट नीतियों का उल्लंघन करने वाले खातों को निलंबित या हटाया जा सकता है",
    ],
    ipHeading: "बौद्धिक संपदा",
    ipBody:
      "सातसहेली पर बनाई और प्रकाशित सभी सामग्री उसके रचनाकार की बौद्धिक संपदा बनी रहती है। हमारे मंच पर प्रकाशित करके, आप सातसहेली को मंच के भीतर आपकी सामग्री प्रदर्शित करने का गैर-अनन्य लाइसेंस प्रदान करते हैं। आप किसी भी समय अपनी सामग्री हटा सकते हैं।",
    contactHeading: "संपर्क",
    contactBody: "इन नीतियों के बारे में प्रश्नों के लिए, कृपया हमसे संपर्क करें",
    contactEmail: "saheli@saatsaheli.com",
    lastUpdated: "अंतिम अपडेट: फरवरी 2026",
  },

  login: {
    brand: "सात सहेली",
    tagline: "आपका डिजिटल किताब मंच",
    logInHeading: "लॉग इन",
    createAccountHeading: "खाता बनाएं",
    labelEmail: "ईमेल",
    labelPassword: "पासवर्ड",
    labelFirstName: "पहला नाम *",
    labelLastName: "उपनाम",
    labelSignupEmail: "ईमेल *",
    labelPhone: "फोन नंबर",
    labelSignupPassword: "पासवर्ड *",
    labelConfirmPassword: "पासवर्ड की पुष्टि करें *",
    placeholderEmail: "अपना ईमेल दर्ज करें",
    placeholderPassword: "अपना पासवर्ड दर्ज करें",
    placeholderFirstName: "पहला नाम",
    placeholderLastName: "उपनाम",
    placeholderPhone: "(वैकल्पिक)",
    placeholderSignupPassword: "कम से कम 6 अक्षर",
    placeholderConfirmPassword: "पासवर्ड फिर से दर्ज करें",
    logInButton: "लॉग इन",
    loggingIn: "लॉग इन हो रहा है...",
    createAccountButton: "खाता बनाएं",
    creatingAccount: "खाता बन रहा है...",
    errorEmailPasswordRequired: "ईमेल और पासवर्ड आवश्यक हैं।",
    errorSignupRequired: "पहला नाम, ईमेल और पासवर्ड आवश्यक हैं।",
    errorPasswordMismatch: "पासवर्ड मेल नहीं खाते।",
    errorPasswordLength: "पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।",
    errorLoginFailed: "लॉगिन विफल। कृपया पुनः प्रयास करें।",
    errorSignupFailed: "साइनअप विफल। कृपया पुनः प्रयास करें।",
    errorGoogleFailed: "Google साइन-इन विफल। कृपया पुनः प्रयास करें।",
    noAccount: "खाता नहीं है?",
    hasAccount: "पहले से खाता है?",
    switchToSignup: "खाता बनाएं",
    switchToLogin: "लॉग इन",
  },

  bookManager: {
    heading: "किताब प्रबंधक",
    createNewBook: "नई किताब बनाएं",
    myDrafts: "मेरे ड्राफ्ट",
    allMyBooks: "मेरी सभी किताबें",
    createHeading: "नई किताब बनाएं",
    placeholderTitle: "किताब का शीर्षक दर्ज करें...",
    createButton: "किताब बनाएं",
    creating: "बना रहे हैं...",
    draftsHeading: "मेरे ड्राफ्ट",
    allBooksHeading: "मेरी सभी किताबें",
    editHeading: "किताब संपादित करें",
    previewHeading: (title) => `पूर्वावलोकन: ${title}`,
    noDrafts: "कोई ड्राफ्ट नहीं मिला।",
    noBooks: "कोई किताब नहीं मिली।",
    saveTitle: "शीर्षक सहेजें",
    saveAsDraft: "ड्राफ्ट के रूप में सहेजें",
    publish: "प्रकाशित करें",
    preview: "पूर्वावलोकन",
    deleteBook: "किताब हटाएं",
    addNewPage: "नया पृष्ठ जोड़ें",
    placeholderPageNumber: "पृष्ठ #",
    placeholderContent: "पृष्ठ सामग्री...",
    placeholderEditContent: "सामग्री",
    addPage: "पृष्ठ जोड़ें",
    pagesCount: (n) => `पृष्ठ (${n})`,
    emptyPage: "(खाली)",
    image1Label: "चित्र 1",
    image2Label: "चित्र 2",
    image1Alt: "चित्र1",
    image2Alt: "चित्र2",
    chooseFile: "फ़ाइल चुनें",
    uploading: "अपलोड हो रहा है...",
    textFormatting: "टेक्स्ट फ़ॉर्मेटिंग",
    fontSans: "सैन्स-सेरिफ",
    fontSerif: "सेरिफ",
    fontMono: "मोनोस्पेस",
    fontCursive: "कर्सिव",
    ariaFontFamily: "फ़ॉन्ट परिवार",
    ariaFontSize: "फ़ॉन्ट आकार",
    ariaFontColor: "फ़ॉन्ट रंग",
    modified: "संशोधित: ",
    backToMenu: "मेनू पर वापस",
    backToEdit: "संपादन पर वापस",
    msgImageUploaded: "चित्र अपलोड हो गया!",
    msgUploadFailed: (err) => `अपलोड विफल: ${err}`,
    msgEnterTitle: "कृपया किताब का शीर्षक दर्ज करें",
    msgBookCreated: "किताब ड्राफ्ट के रूप में बनाई गई!",
    msgCreateFailed: (err) => `किताब बनाने में विफल: ${err}`,
    msgTitleUpdated: "शीर्षक अपडेट हो गया!",
    msgTitleFailed: "शीर्षक अपडेट करने में विफल",
    msgPublished: "किताब प्रकाशित हो गई!",
    msgPublishFailed: "प्रकाशित करने में विफल",
    msgDraftSaved: "ड्राफ्ट सहेजा गया!",
    msgDraftFailed: "ड्राफ्ट सहेजने में विफल",
    confirmDeleteBook: "क्या आप वाकई इस किताब और उसके सभी पृष्ठों को हटाना चाहते हैं?",
    msgBookDeleted: "किताब हटा दी गई!",
    msgDeleteBookFailed: "किताब हटाने में विफल",
    msgPageNumberRequired: "पृष्ठ संख्या आवश्यक है",
    msgPageAdded: "पृष्ठ जोड़ा गया!",
    msgAddPageFailed: "पृष्ठ जोड़ने में विफल",
    msgPageUpdated: "पृष्ठ अपडेट हो गया!",
    msgUpdatePageFailed: "पृष्ठ अपडेट करने में विफल",
    confirmDeletePage: "यह पृष्ठ हटाएं?",
    msgPageDeleted: "पृष्ठ हटा दिया गया!",
    msgDeletePageFailed: "पृष्ठ हटाने में विफल",
    createWithAI: "AI से बनाएं",
    generatingImage: "बना रहे हैं...",
    msgImageGenerated: "AI चित्र बन गया!",
    msgGenerateFailed: (err) => `AI चित्र बनाने में विफल: ${err}`,
    msgEmptyContentForAI: "कृपया AI चित्र के लिए विवरण दर्ज करें।",
    aiPromptDialog: "जो चित्र आप बनाना चाहते हैं उसका वर्णन करें:",
    imageStyleLabel: "चित्र शैली",
    imageStyles: [
      { value: "general", label: "सामान्य" },
      { value: "children", label: "बच्चों की किताब" },
      { value: "poetry", label: "कविता" },
      { value: "story", label: "कहानी" },
      { value: "art", label: "ललित कला" },
      { value: "science", label: "विज्ञान" },
      { value: "politics", label: "राजनीति" },
      { value: "technology", label: "प्रौद्योगिकी" },
      { value: "geography", label: "भूगोल" },
      { value: "history", label: "इतिहास" },
      { value: "fantasy", label: "काल्पनिक" },
      { value: "realistic", label: "यथार्थवादी" },
    ],
    createFromDocument: "दस्तावेज़ से बनाएं",
    uploadDocHeading: "दस्तावेज़ से किताब बनाएं",
    uploadDocHint: "PDF या Word दस्तावेज़ (.pdf, .docx, .doc) अपलोड करें। टेक्स्ट स्वचालित रूप से निकाला जाएगा और पृष्ठों में विभाजित किया जाएगा।",
    uploadDocButton: "अपलोड करें और किताब बनाएं",
    uploadingDoc: "दस्तावेज़ प्रोसेस हो रहा है...",
    msgBookFromDoc: (n) => `दस्तावेज़ से ${n} पृष्ठों वाली किताब बनाई गई!`,
    msgDocUploadFailed: (err) => `दस्तावेज़ अपलोड विफल: ${err}`,
  },

  searchBooks: {
    heading: "किताबें खोजें",
    placeholderBookId: "किताब आईडी",
    placeholderTitle: "शीर्षक",
    placeholderAuthor: "लेखक का नाम",
    ariaBookId: "किताब आईडी से खोजें",
    ariaTitle: "शीर्षक से खोजें",
    ariaAuthor: "लेखक से खोजें",
    ariaStatus: "स्थिति से फ़िल्टर करें",
    statusAll: "सभी स्थितियां",
    statusDraft: "ड्राफ्ट",
    statusPublished: "प्रकाशित",
    statusArchived: "संग्रहीत",
    searching: "खोज रहे हैं...",
    searchButton: "खोजें",
    clearButton: "साफ़ करें",
    resultsHeading: (n) => `परिणाम (${n})`,
    noResults: "कोई किताब नहीं मिली।",
    thId: "आईडी",
    thTitle: "शीर्षक",
    thAuthor: "लेखक",
    thStatus: "स्थिति",
    thModified: "संशोधित",
    emptyAuthor: "\u2014",
    booksHeading: (n) => `किताबें (${n})`,
    backToTable: "तालिका पर वापस",
    byAuthor: (name) => `लेखक: ${name}`,
  },

  account: {
    heading: "मेरा खाता",
    userInfoHeading: "प्रोफ़ाइल",
    labelName: "नाम",
    labelEmail: "ईमेल",
    createProfile: "मेरी प्रोफ़ाइल बनाएं",
    editProfile: "प्रोफ़ाइल संपादित करें",
    viewPublicProfile: "सार्वजनिक प्रोफ़ाइल देखें",
    labelHeadline: "शीर्षक",
    labelLocation: "स्थान",
    labelBio: "मेरे बारे में",
    booksHeading: "मेरी किताबें",
    thTitle: "शीर्षक",
    thStatus: "स्थिति",
    thCreated: "बनाई गई",
    thModified: "संशोधित",
    thActions: "कार्रवाइयां",
    editButton: "संपादित करें",
    emptyState: "आपने अभी तक कोई किताब नहीं बनाई है।",
    loading: "आपकी किताबें लोड हो रही हैं...",
    error: "किताबें लोड करने में विफल। कृपया पुनः प्रयास करें।",
    loginRequired: "कृपया अपना खाता देखने के लिए लॉग इन करें।",
  },

  profile: {
    heading: "मेरी प्रोफ़ाइल बनाएं",
    editHeading: "प्रोफ़ाइल संपादित करें",
    labelDisplayName: "पूरा नाम / प्रदर्शन नाम",
    labelHeadline: "शीर्षक",
    labelProfileImage: "प्रोफ़ाइल चित्र",
    labelLocation: "स्थान",
    labelBio: "मेरे बारे में",
    placeholderDisplayName: "आपका प्रदर्शन नाम",
    placeholderHeadline: "जैसे, कहानियों और रेशम की भावुक बुनकर",
    placeholderLocation: "शहर, देश",
    placeholderBio: "अपनी कहानी अपने शब्दों में बताएं...",
    imageAlt: "प्रोफ़ाइल चित्र",
    uploading: "अपलोड हो रहा है...",
    imageUploaded: "चित्र अपलोड हो गया!",
    imageUploadFailed: "चित्र अपलोड करने में विफल।",
    nameRequired: "प्रदर्शन नाम आवश्यक है।",
    saveButton: "प्रोफ़ाइल सहेजें",
    saving: "सहेज रहे हैं...",
    saved: "प्रोफ़ाइल सहेजी गई!",
    saveFailed: "प्रोफ़ाइल सहेजने में विफल। कृपया पुनः प्रयास करें।",
    backToAccount: "खाते पर वापस",
    loading: "प्रोफ़ाइल लोड हो रही है...",
    loadError: "प्रोफ़ाइल लोड करने में विफल।",
    loginRequired: "कृपया अपनी प्रोफ़ाइल संपादित करने के लिए लॉग इन करें।",
  },

  publicProfile: {
    loading: "प्रोफ़ाइल लोड हो रही है...",
    notFound: "प्रोफ़ाइल नहीं मिली।",
    memberSince: "सदस्य तब से",
    booksHeading: "प्रकाशित किताबें",
    noBooks: "अभी कोई प्रकाशित किताब नहीं है।",
  },

  publicBooks: {
    heading: "प्रकाशित किताबें",
    loading: "किताबें लोड हो रही हैं...",
    error: "किताबें लोड करने में विफल। कृपया पुनः प्रयास करें।",
    emptyState: "अभी कोई प्रकाशित किताब उपलब्ध नहीं है।",
    readButton: "पढ़ें",
    backToBooks: "किताबों पर वापस",
    home: "होम",
    loginPrompt: "अपनी किताबें बनाने और प्रबंधित करने के लिए लॉग इन करें।",
  },

  readBook: {
    backToSearch: "खोज पर वापस",
    home: "होम",
    books: "किताबें",
    prevBook: "पिछली किताब",
    nextBook: "अगली किताब",
  },

  flipBook: {
    pageHeading: (n) => `पृष्ठ ${n}`,
    pageImageAlt: (n, i) => `पृष्ठ ${n} - ${i}`,
    prevPage: "पिछला पृष्ठ",
    nextPage: "अगला पृष्ठ",
    firstPage: "पहला पृष्ठ",
    lastPage: "अंतिम पृष्ठ",
    zoomIn: "ज़ूम इन",
    zoomOut: "ज़ूम आउट",
    zoomReset: "ज़ूम रीसेट",
  },

  pageLayoutEditor: {
    labelBar: "पृष्ठ लेआउट संपादक \u2014 चित्रों को स्थिति में खींचें, आकार बदलने के लिए कोना खींचें",
    image1Label: "चित्र 1",
    image2Label: "चित्र 2",
  },

  category: {
    comingSoon: (title) => `${title} की सामग्री जल्द आ रही है। बने रहें!`,
    backToHome: "होम पर वापस",
  },

  categoryPage: {
    tabBrowse: "ब्राउज़ करें",
    tabCreate: "बनाएं",
    tabMyBooks: "मेरी किताबें",
    noPublished: "इस श्रेणी में अभी कोई प्रकाशित किताब नहीं है।",
    beFirst: "पहली किताब बनाएं!",
    loginToCreate: "सामग्री बनाने के लिए लॉग इन करें",
    createHeading: (title) => `${title} किताब बनाएं`,
    titlePlaceholder: "किताब का शीर्षक दर्ज करें...",
    createButton: "किताब बनाएं",
    createHint: "आपकी किताब ड्राफ्ट के रूप में बनाई जाएगी। पृष्ठ, चित्र जोड़ने और प्रकाशित करने के लिए किताबें पेज का उपयोग करें।",
    myBooksHeading: (title) => `मेरी ${title} किताबें`,
    noMyBooks: "आपने अभी तक इस श्रेणी में कोई किताब नहीं बनाई है।",
    createFirst: "अपनी पहली किताब बनाएं",
    enterTitle: "कृपया शीर्षक दर्ज करें",
    bookCreated: "किताब ड्राफ्ट के रूप में बनाई गई!",
    createFailed: "किताब बनाने में विफल",
    confirmDelete: "क्या यह किताब हटाएं?",
    bookDeleted: "किताब हटा दी गई!",
    deleteFailed: "किताब हटाने में विफल",
    bookPublished: "किताब प्रकाशित हो गई!",
    publishFailed: "प्रकाशित करने में विफल",
    backToBrowse: "वापस",
    descriptions: {
      art: "समुदाय के साथ कला सामग्री का अन्वेषण और साझा करें",
      music: "समुदाय के साथ संगीत सामग्री का अन्वेषण और साझा करें",
      writing: "समुदाय के साथ लेखन सामग्री का अन्वेषण और साझा करें",
      tech: "समुदाय के साथ तकनीक सामग्री का अन्वेषण और साझा करें",
      creativity: "समुदाय के साथ रचनात्मकता सामग्री का अन्वेषण और साझा करें",
      community: "समुदाय के साथ सामुदायिक सामग्री का अन्वेषण और साझा करें",
    },
  },

  techPage: {
    heading: "तकनीक",
    description: "कई आयामों में प्रौद्योगिकी विषयों का अन्वेषण करें",
    tabTechnical: "तकनीकी",
    tabCareer: "करियर और उद्योग",
    tabCommunity: "समुदाय और प्रतिनिधित्व",
    tabOther: "अन्य",
    descTechnical: "प्रोग्रामिंग, कोडिंग ट्यूटोरियल, टूल्स और तकनीकी संसाधन",
    descCareer: "तकनीकी करियर, नौकरी कौशल, उद्योग अंतर्दृष्टि और पेशेवर विकास",
    descCommunity: "तकनीक में महिलाएं, विविधता, समावेशन और प्रतिनिधित्व की कहानियां",
    descOther: "विविध तकनीकी विषय, रुझान और दिलचस्प खोजें",
    comingSoon: "सामग्री जल्द आ रही है। बने रहें!",
  },

  admin: {
    heading: "व्यवस्थापक डैशबोर्ड",
    tabStats: "आंकड़े",
    tabUsers: "उपयोगकर्ता",
    tabBooks: "किताबें",
    totalUsers: "कुल उपयोगकर्ता",
    activeUsers: "सक्रिय उपयोगकर्ता",
    blockedUsers: "अवरुद्ध उपयोगकर्ता",
    adminCount: "व्यवस्थापक",
    totalBooks: "कुल किताबें",
    publishedBooks: "प्रकाशित",
    draftBooks: "ड्राफ्ट",
    colName: "नाम",
    colEmail: "ईमेल",
    colRole: "भूमिका",
    colStatus: "स्थिति",
    colLastLogin: "अंतिम लॉगिन",
    colActions: "कार्रवाइयां",
    colTitle: "शीर्षक",
    colAuthor: "लेखक",
    colBookStatus: "स्थिति",
    colModified: "संशोधित",
    roleUpdated: "भूमिका अपडेट हो गई!",
    roleUpdateFailed: "भूमिका अपडेट करने में विफल",
    statusUpdated: "स्थिति अपडेट हो गई!",
    statusUpdateFailed: "स्थिति अपडेट करने में विफल",
    confirmDeleteBook: "क्या आप वाकई इस किताब को हटाना चाहते हैं?",
    bookDeleted: "किताब हटा दी गई!",
    bookDeleteFailed: "किताब हटाने में विफल",
  },

  chat: {
    roomsHeading: "चैट रूम",
    noMessages: "अभी तक कोई संदेश नहीं। बातचीत शुरू करें!",
    selectRoom: "चैट शुरू करने के लिए एक रूम चुनें",
    placeholder: "संदेश लिखें...",
    sendButton: "भेजें",
    sending: "...",
    deleteMessage: "हटाएं",
  },

  dropdown: {
    defaultText: "चुनें",
  },
};

// Default export for backward compatibility during transition
const strings = en;
export default strings;
