--
-- PostgreSQL database dump
--

\restrict xjIzQEZW24FSdWUTWhOPNRHZY9ALKbyi8IIrdNQ7mbsJzM0rnf1LGLv17PLufAT

-- Dumped from database version 17.8 (a48d9ca)
-- Dumped by pg_dump version 17.9 (Postgres.app)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: advertisements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.advertisements (
    id bigint NOT NULL,
    active boolean,
    animation character varying(255),
    content_type character varying(255),
    created_date timestamp(6) without time zone,
    html_content text,
    image_url character varying(255),
    link_url character varying(255),
    modified_date timestamp(6) without time zone,
    title character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    placement character varying(255)
);


--
-- Name: advertisements_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.advertisements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.advertisements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: articles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.articles (
    id bigint NOT NULL,
    content text,
    created_date timestamp(6) without time zone,
    headline character varying(255) NOT NULL,
    image_url character varying(255),
    modified_date timestamp(6) without time zone,
    status character varying(255),
    user_id bigint NOT NULL,
    content_type character varying(255),
    category character varying(255)
);


--
-- Name: articles_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.articles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.articles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: books; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.books (
    id bigint NOT NULL,
    category character varying(255),
    created_date timestamp(6) without time zone,
    modified_date timestamp(6) without time zone,
    status character varying(255),
    title character varying(255),
    user_id bigint,
    language character varying(255),
    page_size character varying(40)
);


--
-- Name: books_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.books ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.books_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_messages (
    id bigint NOT NULL,
    created_date timestamp(6) without time zone,
    is_deleted boolean,
    message text,
    room_id bigint,
    sender_id bigint,
    sender_name character varying(255)
);


--
-- Name: chat_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chat_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_rooms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_rooms (
    id bigint NOT NULL,
    category character varying(255),
    created_date timestamp(6) without time zone,
    description text,
    modified_date timestamp(6) without time zone,
    name character varying(255)
);


--
-- Name: chat_rooms_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chat_rooms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_rooms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.comments (
    id bigint NOT NULL,
    content text,
    created_date timestamp(6) without time zone,
    is_deleted boolean,
    target_id bigint,
    target_type character varying(255),
    user_id bigint,
    user_name character varying(255)
);


--
-- Name: comments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    recipient_user_id bigint,
    actor_user_id bigint,
    actor_name character varying(255),
    type character varying(255),
    target_type character varying(255),
    target_id bigint,
    target_title character varying(255),
    comment_id bigint,
    message text,
    link character varying(255),
    is_read boolean,
    admin_copy boolean,
    created_date timestamp(6) without time zone
);


--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: idx_notifications_recipient; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_recipient ON public.notifications USING btree (recipient_user_id);


--
-- Name: idx_notifications_recipient_unread; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_recipient_unread ON public.notifications USING btree (recipient_user_id, is_read);


--
-- Name: contact_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contact_messages (
    id bigint NOT NULL,
    created_date timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    message text NOT NULL,
    name character varying(255) NOT NULL,
    subject character varying(255),
    updated_date timestamp(6) without time zone,
    status character varying(255),
    category character varying(255),
    rating character varying(255),
    tracking_id character varying(32)
);


--
-- Name: contact_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.contact_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.contact_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: content_likes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.content_likes (
    id bigint NOT NULL,
    created_date timestamp(6) without time zone,
    target_id bigint,
    target_type character varying(255),
    user_id bigint
);


--
-- Name: content_likes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.content_likes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.content_likes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: favorites; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.favorites (
    id bigint NOT NULL,
    created_date timestamp(6) without time zone,
    target_id bigint,
    target_type character varying(255),
    user_id bigint
);


--
-- Name: favorites_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.favorites ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.favorites_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: galleries; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.galleries (
    id bigint NOT NULL,
    cover_image_url character varying(255),
    created_date timestamp(6) without time zone,
    description text,
    modified_date timestamp(6) without time zone,
    status character varying(255),
    title character varying(255),
    user_id bigint
);


--
-- Name: galleries_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.galleries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.galleries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: gallery_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.gallery_images (
    id bigint NOT NULL,
    caption character varying(255),
    created_date timestamp(6) without time zone,
    gallery_id bigint,
    image_url character varying(255),
    order_index integer
);


--
-- Name: gallery_images_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.gallery_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gallery_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hero_slides; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.hero_slides (
    slot smallint NOT NULL,
    name character varying(120),
    source_url text,
    image_url text,
    updated_at timestamp(6) without time zone,
    updated_by bigint,
    CONSTRAINT hero_slides_pkey PRIMARY KEY (slot),
    CONSTRAINT hero_slides_slot_range CHECK (slot >= 1 AND slot <= 8)
);


--
-- Name: logins; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.logins (
    id bigint NOT NULL,
    account_created_date timestamp(6) without time zone,
    created_date timestamp(6) without time zone,
    email character varying(255),
    last_login_date timestamp(6) without time zone,
    password character varying(255),
    provider character varying(255),
    status character varying(255),
    user_id bigint,
    must_change_password boolean,
    temp_password character varying(255)
);


--
-- Name: logins_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.logins ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.logins_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: marketplace_listings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.marketplace_listings (
    id bigint NOT NULL,
    category character varying(255),
    item_condition character varying(255),
    contact_info character varying(255),
    created_date timestamp(6) without time zone,
    description text,
    image1_url character varying(255),
    image2_url character varying(255),
    image3_url character varying(255),
    image4_url character varying(255),
    modified_date timestamp(6) without time zone,
    price character varying(255) NOT NULL,
    price_amount numeric(12,2),
    currency character varying(255),
    status character varying(255),
    quantity integer DEFAULT 1,
    delivery_fee numeric(12,2),
    title character varying(255) NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: marketplace_listings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.marketplace_listings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.marketplace_listings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pages (
    id bigint NOT NULL,
    book_id bigint,
    content text,
    created_date timestamp(6) without time zone,
    format text,
    image_url character varying(255),
    image_url_2 character varying(255),
    modified_date timestamp(6) without time zone,
    page_number integer
);


--
-- Name: pages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: podcasts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.podcasts (
    id bigint NOT NULL,
    audio_url character varying(255),
    category character varying(255),
    cover_image_url character varying(255),
    created_date timestamp(6) without time zone,
    description text,
    duration_seconds integer,
    language character varying(255),
    modified_date timestamp(6) without time zone,
    status character varying(255),
    title character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    youtube_url character varying(255)
);


--
-- Name: podcasts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.podcasts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.podcasts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recipe_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recipe_images (
    id bigint NOT NULL,
    caption character varying(255),
    created_date timestamp(6) without time zone,
    image_url character varying(255),
    order_index integer,
    recipe_id bigint
);


--
-- Name: recipe_images_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recipe_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recipe_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recipes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.recipes (
    id bigint NOT NULL,
    created_date timestamp(6) without time zone,
    cuisine character varying(255),
    ingredients text,
    instructions text,
    modified_date timestamp(6) without time zone,
    recipe_name character varying(255) NOT NULL,
    status character varying(255),
    user_id bigint NOT NULL
);


--
-- Name: recipes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.recipes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recipes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: site_visits; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.site_visits (
    id bigint NOT NULL,
    browser character varying(255),
    device character varying(255),
    page_path character varying(255),
    referrer character varying(255),
    session_id character varying(255),
    user_agent character varying(255),
    user_id bigint,
    visited_at timestamp(6) without time zone,
    visitor_id character varying(255)
);


--
-- Name: site_visits_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.site_visits ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.site_visits_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    age integer,
    created_date timestamp(6) without time zone,
    email character varying(255),
    first_name character varying(255),
    gender character varying(255),
    last_name character varying(255),
    middle_name character varying(255),
    modified_date timestamp(6) without time zone,
    phone_number character varying(255),
    role character varying(255),
    bio text,
    display_name character varying(255),
    headline character varying(255),
    location character varying(255),
    profile_image_url character varying(255),
    fields text,
    interests text,
    plan character varying(255),
    team_role character varying(255),
    occupation character varying(255)
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: advertisements advertisements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.advertisements
    ADD CONSTRAINT advertisements_pkey PRIMARY KEY (id);


--
-- Name: articles articles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.articles
    ADD CONSTRAINT articles_pkey PRIMARY KEY (id);


--
-- Name: books books_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.books
    ADD CONSTRAINT books_pkey PRIMARY KEY (id);


--
-- Name: chat_messages chat_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT chat_messages_pkey PRIMARY KEY (id);


--
-- Name: chat_rooms chat_rooms_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_rooms
    ADD CONSTRAINT chat_rooms_pkey PRIMARY KEY (id);


--
-- Name: comments comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (id);


--
-- Name: contact_messages contact_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contact_messages
    ADD CONSTRAINT contact_messages_pkey PRIMARY KEY (id);


--
-- Name: content_likes content_likes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_likes
    ADD CONSTRAINT content_likes_pkey PRIMARY KEY (id);


--
-- Name: favorites favorites_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT favorites_pkey PRIMARY KEY (id);


--
-- Name: galleries galleries_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.galleries
    ADD CONSTRAINT galleries_pkey PRIMARY KEY (id);


--
-- Name: gallery_images gallery_images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.gallery_images
    ADD CONSTRAINT gallery_images_pkey PRIMARY KEY (id);


--
-- Name: logins logins_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.logins
    ADD CONSTRAINT logins_pkey PRIMARY KEY (id);


--
-- Name: marketplace_listings marketplace_listings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.marketplace_listings
    ADD CONSTRAINT marketplace_listings_pkey PRIMARY KEY (id);


--
-- Name: pages pages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pages
    ADD CONSTRAINT pages_pkey PRIMARY KEY (id);


--
-- Name: podcasts podcasts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.podcasts
    ADD CONSTRAINT podcasts_pkey PRIMARY KEY (id);


--
-- Name: recipe_images recipe_images_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipe_images
    ADD CONSTRAINT recipe_images_pkey PRIMARY KEY (id);


--
-- Name: recipes recipes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.recipes
    ADD CONSTRAINT recipes_pkey PRIMARY KEY (id);


--
-- Name: site_visits site_visits_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.site_visits
    ADD CONSTRAINT site_visits_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: favorites uk781pmjx7kf279uopjhmbwnqhl; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.favorites
    ADD CONSTRAINT uk781pmjx7kf279uopjhmbwnqhl UNIQUE (user_id, target_type, target_id);


--
-- Name: logins ukdffejhld3kdl9ex8n0d7rd6b; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.logins
    ADD CONSTRAINT ukdffejhld3kdl9ex8n0d7rd6b UNIQUE (email);


--
-- Name: logins uknxts7bjbp0m80d4ul22ktba2a; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.logins
    ADD CONSTRAINT uknxts7bjbp0m80d4ul22ktba2a UNIQUE (user_id);


--
-- Name: content_likes ukq0renxup427se2cw9p7q03t1r; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.content_likes
    ADD CONSTRAINT ukq0renxup427se2cw9p7q03t1r UNIQUE (user_id, target_type, target_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict xjIzQEZW24FSdWUTWhOPNRHZY9ALKbyi8IIrdNQ7mbsJzM0rnf1LGLv17PLufAT


--
-- Marketplace cart & orders (added for the buy/sell checkout flow).
-- Tables are auto-created by Hibernate (ddl-auto=update); definitions below
-- mirror the JPA entities for documentation/parity.
--

CREATE TABLE public.marketplace_cart_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    user_id bigint NOT NULL,
    listing_id bigint NOT NULL,
    added_date timestamp(6) without time zone,
    CONSTRAINT uq_cart_user_listing UNIQUE (user_id, listing_id)
);

CREATE TABLE public.marketplace_orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    order_number character varying(255) NOT NULL UNIQUE,
    user_id bigint NOT NULL,
    buyer_email character varying(255),
    buyer_name character varying(255),
    subtotal numeric(12,2),
    currency character varying(255),
    status character varying(255),
    stripe_session_id character varying(255) UNIQUE,
    stripe_payment_intent character varying(255),
    tracking_number character varying(255),
    tracking_carrier character varying(255),
    created_date timestamp(6) without time zone,
    paid_date timestamp(6) without time zone,
    cancelled_date timestamp(6) without time zone,
    cancel_reason character varying(255),
    stripe_refund_id character varying(255),
    ship_name character varying(255),
    ship_country character varying(255),
    ship_line1 character varying(255),
    ship_line2 character varying(255),
    ship_city character varying(255),
    ship_state character varying(255),
    ship_postal_code character varying(255)
);

CREATE TABLE public.marketplace_order_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    order_id bigint,
    listing_id bigint,
    title character varying(255),
    price_amount numeric(12,2),
    currency character varying(255),
    seller_id bigint,
    image_url character varying(255)
);
