spring.application.name=SaatSaheli
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.web.resources.static-locations=file:./uploads/
server.port=8081
#Server [localhost]:
#Database [postgres]:
#Port [5432]:
#Username [postgres]:
#Password for user postgres:

#psql (17.4)

#postgres=# CREATE DATABASE saatsahelidb
#postgres-# CREATE USER saatsaheli WITH ENCRYPTED PASSWORD Ch4884ch#12
#postgres-# GRANT ALL PRIVILEDGES ON DATABASE saatsahelidb TO saatsaheli
